# Generated by Django 6.0.5 on 2026-05-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrosequipe',
            name='foto',
            field=models.ImageField(upload_to='equipe/'),
        ),
    ]
