# Generated by Django 6.0.5 on 2026-05-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_projetos'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Apresentação/'),
        ),
    ]
